//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zvuk.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Studiya_zvukozapisiEntities : DbContext
    {
        public Studiya_zvukozapisiEntities()
            : base("name=Studiya_zvukozapisiEntities")
        {
        }

        private static Studiya_zvukozapisiEntities _context;
        public static Studiya_zvukozapisiEntities GetContext()
        {
            if (_context == null)
                _context = new Studiya_zvukozapisiEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<Execuor> Execuor { get; set; }
        public virtual DbSet<Music> Music { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
