//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zvuk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public int MusicID { get; set; }
        public int ExecuorID { get; set; }
        public int AlbumID { get; set; }
        public string Author { get; set; }
        public string Genre { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Execuor Execuor { get; set; }
    }
}
